import { PaymentKpiCard, PaymentTableRow } from './PaymentPresentation';
import { ExcelIcon } from '../../../components/ui/ExcelIcon';
import PaymentMobileCard from './PaymentMobileCard';

const ProgressCard = ({ title, icon, percent, leftLabel, rightLabel, leftColor = 'bg-primary', rightColor = 'bg-surface-container-highest' }) => (
  <div className="bg-surface border border-outline-variant rounded-xl p-4 shadow-sm flex flex-col gap-2"><div className="flex justify-between items-end"><div className="flex items-center gap-2"><span className="material-symbols-outlined text-[18px] text-primary" translate="no">{icon}</span><span className="text-xs font-bold text-on-surface uppercase tracking-wider">{title}</span></div>{percent !== undefined && <span className="font-data-mono font-bold text-primary text-sm">{percent.toFixed(1)}%</span>}</div><div className="relative w-full h-3 bg-surface-container-highest rounded-full overflow-hidden flex"><div className={`h-full transition-all duration-1000 ease-out ${leftColor}`} style={{ width: `${Math.min(percent ?? 0, 100)}%` }} /><div className={`h-full flex-1 ${rightColor}`} /></div><div className="flex justify-between text-[10px] text-on-surface-variant font-medium mt-1"><span>{leftLabel}</span><span>{rightLabel}</span></div></div>
);

export const PaymentsDashboard = ({ filterMes, onFilterChange, year, months, formatPeriod, showAnulados, onShowAnuladosChange, onRegister, canRegister, metrics, formatCurrency }) => {
  const cashPercent = metrics.totalRecaudado > 0 ? (metrics.recaudadoEfectivo / metrics.totalRecaudado) * 100 : 0;
  return <>
    <div className="mb-4 flex flex-col md:flex-row justify-between items-start md:items-end gap-4"><div><h2 className="text-2xl text-on-surface font-bold leading-tight">Modulo de Pagos</h2><p className="text-sm text-on-surface-variant">Seguimiento detallado de ingresos por servicios energéticos</p></div><div className="flex flex-wrap items-end gap-3"><label className="flex flex-col gap-0.5"><span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-wider pl-1">Periodo a Filtrar</span><span className="relative"><select className="appearance-none border border-outline-variant rounded-md pl-3 pr-8 py-1.5 h-8 bg-surface-container-lowest text-on-surface text-xs focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary min-w-[180px] transition-all font-medium cursor-pointer shadow-sm hover:border-primary/50" value={filterMes} onChange={(event) => onFilterChange(event.target.value)}><option value="Todos">Todos los meses ({year})</option><option value="TodosHistorico">Histórico (Todos los años)</option>{months.map((month) => <option key={month} value={month}>{formatPeriod(month)}</option>)}</select><span className="material-symbols-outlined absolute right-2 top-1/2 -translate-y-1/2 pointer-events-none text-on-surface-variant text-[16px]" translate="no">expand_more</span></span></label><label className="flex items-center gap-1.5 cursor-pointer"><span className="relative"><input type="checkbox" className="sr-only" checked={showAnulados} onChange={(event) => onShowAnuladosChange(event.target.checked)} /><span className={`block w-8 h-4 rounded-full transition-colors ${showAnulados ? 'bg-error' : 'bg-surface-variant'}`} /><span className={`absolute left-1 top-0.5 bg-white w-3 h-3 rounded-full transition-transform ${showAnulados ? 'translate-x-3.5' : ''}`} /></span><span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">Ver Anulados</span></label><button type="button" onClick={onRegister} disabled={!canRegister} className={`flex items-center px-3 py-1.5 h-8 font-bold rounded-md transition-opacity shadow-sm text-xs ${canRegister ? 'bg-primary text-on-primary hover:opacity-90 active:scale-95' : 'bg-surface-variant text-on-surface-variant cursor-not-allowed opacity-70'}`}><span className="material-symbols-outlined mr-1 text-[16px]" translate="no">add_card</span>Registrar Pago</button></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3 mb-4"><PaymentKpiCard icon="request_quote" label="Total Facturado" value={`S/ ${formatCurrency(metrics.totalFacturado)}`} subtitle="En el periodo seleccionado" /><PaymentKpiCard icon="account_balance_wallet" label="Total Recaudado" value={`S/ ${formatCurrency(metrics.totalRecaudado)}`} subtitle="Ingresos reales" colorScheme="emerald" subtitleIcon="trending_up" /><PaymentKpiCard icon="checklist" label="Avance de Cobro" value={<>{metrics.facturasPagadas}<span className="font-data-mono text-[10px] text-on-surface-variant font-bold">/ {metrics.totalFacturas}</span></>} subtitle="Facturas pagadas" colorScheme="tertiary" /><PaymentKpiCard icon="pending_actions" label="Pendiente de Cobro" value={`S/ ${formatCurrency(metrics.pendienteRecaudar)}`} subtitle="Resto que falta cobrar" colorScheme="amber" /></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><ProgressCard title="Avance de Recaudación" icon="monitoring" percent={metrics.porcentajeRecaudado} leftLabel={`Recaudado (S/ ${formatCurrency(metrics.totalRecaudado)})`} rightLabel={`Pendiente (S/ ${formatCurrency(metrics.pendienteRecaudar)})`} /><ProgressCard title="Ingresos por Método" icon="pie_chart" percent={cashPercent} leftLabel={`Efectivo (S/ ${formatCurrency(metrics.recaudadoEfectivo)})`} rightLabel={`Transferencia (S/ ${formatCurrency(metrics.recaudadoTransferencia)})`} leftColor="bg-emerald-500" rightColor="bg-indigo-500" /></div>
  </>;
};

export const PaymentHistoryTable = ({ payments, loading, searchTerm, onSearchChange, showAnulados, onToggleAnulados, onExportExcel, onExportPDF, onExportTickets, fallbackMap, onSelect, onOpenMenu, openMenuPaymentId, getTipoInfo, formatCurrency }) => (
  <div className="bg-surface-container-lowest border border-outline-variant rounded-lg overflow-hidden shadow-sm">
    <div className="px-4 py-3 border-b border-outline-variant flex flex-col md:flex-row justify-between items-start md:items-center gap-3 bg-surface-container-low">
      <h4 className="text-base font-bold text-on-surface">Historial de Pagos</h4>
      <div className="grid grid-cols-2 md:flex md:flex-wrap items-center gap-2 w-full md:w-auto">
        <div className="relative col-span-2 md:col-auto"><span className="material-symbols-outlined absolute left-2.5 top-1/2 -translate-y-1/2 text-on-surface-variant text-[16px]" translate="no">search</span><input type="search" placeholder="Buscar por socio o recibo..." value={searchTerm} onChange={(event) => onSearchChange(event.target.value)} className="pl-8 pr-3 py-1.5 h-8 border border-outline-variant rounded-md text-xs focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary w-full md:w-48 bg-white transition-all" /></div>
        <button type="button" onClick={onToggleAnulados} className={`flex items-center justify-center gap-1.5 px-2.5 py-1.5 h-8 font-bold text-xs rounded-md transition-colors border ${showAnulados ? 'bg-amber-500/15 text-amber-800 border-amber-500/30' : 'bg-white text-on-surface-variant border-outline-variant hover:bg-surface-container'}`}><span className="material-symbols-outlined text-[16px]" translate="no">{showAnulados ? 'visibility_off' : 'visibility'}</span>{showAnulados ? 'Ocultar Anulados' : 'Ver Anulados'}</button>
        <button type="button" onClick={onExportExcel} className="flex items-center justify-center gap-1.5 px-2.5 py-1.5 h-8 font-bold text-xs rounded-md border border-[#107C41]/20 bg-[#107C41]/10 text-[#107C41] hover:bg-[#107C41]/20 transition-colors"><ExcelIcon className="w-4 h-4" />Excel</button>
        <button type="button" onClick={onExportPDF} className="flex items-center justify-center gap-1.5 px-2.5 py-1.5 h-8 font-bold text-xs rounded-md border border-outline-variant bg-error/10 text-error hover:bg-error/20 transition-colors"><span className="material-symbols-outlined text-[16px]" translate="no">picture_as_pdf</span>Reporte PDF</button>
        <button type="button" onClick={onExportTickets} className="flex items-center justify-center gap-1.5 px-2.5 py-1.5 h-8 font-bold text-xs rounded-md border border-outline-variant bg-primary/10 text-primary hover:bg-primary/20 transition-colors"><span className="material-symbols-outlined text-[16px]" translate="no">print</span>Tickets A5</button>
      </div>
    </div>
    <div className="md:hidden divide-y divide-outline-variant/60 bg-surface">
      {loading ? <div className="p-8 text-center text-on-surface-variant">Cargando pagos...</div> : payments.length === 0 ? <div className="p-8 text-center text-on-surface-variant">No se encontraron pagos</div> : payments.map((payment) => <PaymentMobileCard key={payment.id} payment={payment} previousAmount={fallbackMap.get(payment.id) || 0} onSelect={onSelect} onOpenMenu={onOpenMenu} isMenuOpen={openMenuPaymentId === payment.id} getTypeInfo={getTipoInfo} formatCurrency={formatCurrency} />)}
    </div>
    <div className="hidden md:block overflow-auto max-h-[calc(100vh-280px)] custom-scrollbar">
      <table className="w-full text-left border-collapse table-auto whitespace-nowrap">
        <thead className="bg-surface-container-lowest border-b border-outline-variant text-on-surface-variant text-[11px] uppercase tracking-wider sticky top-0 z-10 shadow-sm">
          <tr><th className="px-4 py-2 font-semibold">Socio</th><th className="px-4 py-2 font-semibold">Detalle / Fecha</th><th className="px-4 py-2 font-semibold text-center">Estado</th><th className="px-4 py-2 font-semibold text-right">Monto</th><th className="px-4 py-2 font-semibold text-right w-16">Acciones</th></tr>
        </thead>
        <tbody className="divide-y divide-outline-variant/50 bg-surface">
          {loading ? <tr><td colSpan="5" className="text-center p-8 text-on-surface-variant">Cargando pagos...</td></tr> : payments.length === 0 ? <tr><td colSpan="5" className="text-center p-8 text-on-surface-variant">No se encontraron pagos</td></tr> : payments.map((payment) => <PaymentTableRow key={payment.id} pago={payment} fallbackPrevio={fallbackMap.get(payment.id) || 0} onSelect={onSelect} onOpenMenu={onOpenMenu} isMenuOpen={openMenuPaymentId === payment.id} getTipoInfo={getTipoInfo} formatCurrency={formatCurrency} />)}
        </tbody>
      </table>
    </div>
  </div>
);
